version: "3"
services:
nginx:
  image: nginx:latest
  container_name: nginx
  port:
   - "80:80"
   - "443:443"
  environment:
   - DOMAIN=1.heattreater.in
   - PROXY_URL=wordpress
   - PROXY_PORT=80
wordpress:
  image: wordpress:latest
  container_name: wordpress
  volumes: wp-data:/var/www/html
  port:
   - "8080:8080"
  restart: always
  environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
   db_data:
   wp_data:
db:
    image: mysql:5.7
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
      - 33060


